LANGUAGES = {
    'nl': 'dutch',
    'fi': 'finnish',
    'fr': 'french',
    'de': 'german',
    'it': 'italian',
    'ko': 'korean',
    'no': 'norwegian',
    'pl': 'polish', 
    'ro': 'romanian',    
    'zh-cn': 'chinese (simplified)',
    'zh-tw': 'chinese (traditional)',
    'es': 'spanish',
    'en': 'english',
    'ar': 'arabic',
    'ru': 'russian',
    'ja': 'japanese',
    'da': 'danish',
}

SPACE_TOPICS = [
    "Space",
    "Mars",
    "Moon",
    "jet fuel",
    "null gravity",
    "zero gravity",
    "fire retardant", 
    "hydrogen",
    "Oxygen",
    "planet",
    "rover",
    "ISS",
    "NASA",
    "SpaceX",
    "BlueOrigin",
    "Saturn",
    "Space shuttle",
    "Saturn V",
    "planet",
    "solar",
    "Appolo missions",
    "solar radiation",
    "Satellite",
    "Sabatier method",
    "electrolysis",
    "asteroid",
    "space suit",
    "galaxy",
    "self propulsion",
    "Density",
    "Doppler effect",
    "Electromagnetic",
    "Gravitation",
    "Galexy"
    "Halo orbit",
    "Kelvin",
    "Light Speed",
    "Light Year",
    "Mass",
    "Milky Way",
    "Nucleus",
    "Pathfinder",
    "Plasma",
    "Quasar",
    "Velocity",
    "Acceleration",
    "Walking Orbit",
    "Weight",
    "Zenith"
]